package io.github.andrewbgm.reactswingserver.impl

import io.github.andrewbgm.reactswingserver.api.*

enum class MessageTypes : MessageType {
  APPEND_CHILD_TO_CONTAINER,
  APPEND_CHILD,
  APPEND_INITIAL_CHILD,
  CLEAR_CONTAINER,
  COMMIT_TEXT_UPDATE,
  COMMIT_UPDATE,
  CREATE_TEXT_INSTANCE,
  CREATE_INSTANCE,
  FREE_CALLBACK,
  HIDE_INSTANCE,
  HIDE_TEXT_INSTANCE,
  INSERT_BEFORE,
  INSERT_IN_CONTAINER_BEFORE,
  INVOKE_CALLBACK,
  REMOVE_CHILD_FROM_CONTAINER,
  REMOVE_CHILD,
  START_APPLICATION,
  STOP_APPLICATION,
  UNHIDE_INSTANCE,
  UNHIDE_TEXT_INSTANCE,
}
